backend:
  name: git-gateway
  branch: main   # Change to your default branch if it's not 'main'

media_folder: "static/images/uploads"    # Path to store uploaded images
public_folder: "/images/uploads"         # Path the CMS and site use to access images

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{slug}}/index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Images", name: "images", widget: "image", multiple: true, media_folder: "images", public_folder: "images"}